# -*- coding: utf-8 -*-
"""rmbs_auditor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePWazP2mFxsy7CqwdgbAmRxJQY1_zaAQ
"""

pip install google-genai pypdf

import os
from pypdf import PdfReader
from google import genai
from google.genai import types

# -------------------------------------------------------------
# SETUP CONFIGURATION
# -------------------------------------------------------------
# Paste your free Gemini API key here
API_KEY = "YOUR_FREE_GEMINI_API_KEY_HERE" # Redacted for security


# Path to your downloaded public Australian RMBS/ABS Information Memorandum
PDF_PATH = r"/content/sample_data/ABS Annual Report 2024-25_final.pdf"

# Initialize the official Google GenAI Client
client = genai.Client(api_key=API_KEY)

# -------------------------------------------------------------
# STEP 1: EXTRACT & CHUNK THE PDF (With Page Numbers)
# -------------------------------------------------------------
print("—— Reading PDF and mapping pages...")
reader = PdfReader(PDF_PATH)
document_pages = []

# Loop through pages and format them with headers so the LLM knows the page source
for page_num, page in enumerate(reader.pages, start=1):
    text = page.extract_text()
    if text:
        document_pages.append(f"--- START OF PAGE {page_num} ---\n{text}\n--- END OF PAGE {page_num} ---")

# Combine the document text
full_document_text = "\n\n".join(document_pages)

# -------------------------------------------------------------
# STEP 2: DEFINE THE AD-LEVEL INSTITUTIONAL SYSTEM PROMPT
# -------------------------------------------------------------
system_instruction = """
You are a Senior Credit Ratings Specialist in the Structured Finance division at S&P Global Ratings.
Your task is to audit Australian RMBS or ABS Information Memorandums for key structural credit parameters.

For every parameter requested, you MUST adhere to these strict data governance rules:
1. Extract the exact value, percentage, trigger, or rule.
2. Provide the EXACT Page Number(s) where this information was found.
3. If a parameter is missing or not mentioned, explicitly state 'Not found in document'.
4. Do NOT hallucinate or assume metrics. If it is not explicitly written in the provided text, do not guess.
"""

user_prompt = f"""
Please analyze the following extracted text from an Australian Structured Finance transaction document and locate these 4 specific parameters:

1. Clean-Up Call Option: What is the exact outstanding pool balance percentage trigger that allows the originator to redeem the notes early? (e.g., 10%)
2. Sequential Pay Triggers: What performance metrics or delinquency triggers (e.g., 90+ day delinquencies hitting a certain percentage) force the waterfall to switch from pro-rata to sequential?
3. Servicer Commingling & Backup Risk: Is there a named Backup Servicer, and what is the required timeline to transition operations if the primary servicer fails?
4. Credit Enhancement Levels: Detail the structural credit support or subordination levels for the classes of notes (e.g., Class A down to Class G/Equity).

Format your output clearly with bullet points, using bold text for the answers and citations.

--- START OF TRANSACTION DOCUMENT ---
{full_document_text[:80000]}
--- END OF TRANSACTION DOCUMENT ---
"""
# Note: [:80000] keeps it safely within free tier context boundaries for testing.
# Gemini 1.5 Pro/Flash can handle the entire 300+ page document easily if you feed the whole string.

# -------------------------------------------------------------
# STEP 3: EXECUTE THE AGENTIC AUDIT
# -------------------------------------------------------------
print("—— Ingesting data into Gemini and running audit...")

response = client.models.generate_content(
    model='gemini-3.8-flash',
    contents=user_prompt,
    config=types.GenerateContentConfig(
        system_instruction=system_instruction,
        temperature=0.0,
    ),
)

# -------------------------------------------------------------
# STEP 4: OUTPUT THE RECONCILED AUDIT REPORT
# -------------------------------------------------------------
print("\n—— --- S&P GLOBAL PROTOTYPE AUDIT REPORT --- \n")
print(response.text)
print("\n-------------------------------------------------")
print("✅ Audit complete. Human-in-the-loop review required before committee submission.")